import Sidebar from '@/components/Sidebar'
import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mysocialpays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Side Bar */}
        <Sidebar />


        {/* Feed */}



        {/* Widgets */}


        {/* Modal */}

      </main>

    </div>
  )
}
