import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mysocialpays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World</h1>

    </div>
  )
}
